version: '3'

networks:
  ondoor:

services:
  nginx:
#    image: docker.io/nginx:alpine
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: app-nginx
    networks:
      - ondoor
    ports:
      - "80:80"
    volumes:
      - ./source:/source
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d/:/etc/nginx/conf.d/:ro
      - ./log/nginx:/var/log/nginx
    links:
      - php-fpm:fpm

  php-fpm:
#    image: daocloud.io/wuyun_1/php-fpm-7_2-alpine:latest
    build:
      context: ./php-fpm
      dockerfile: Dockerfile
    container_name: app-php
    networks:
      - ondoor
    ports:
      - "9000:9000"
    links:
      - mysql:mysql
      - redis:redis
    volumes:
      - ./source:/source
      - ./log/supervisor:/var/log/supervisor
      - ./php-fpm/php.ini:/usr/local/etc/php/php.ini:ro
      - ./php-fpm/supervisord.conf:/etc/supervisord.conf
      - ./php-fpm/supervisor.d:/etc/supervisor.d
    command: supervisord -c /etc/supervisord.conf

  mysql:
    image: mysql:5.7.16
    container_name: app-mysql
    networks:
      - ondoor
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/mysqld.cnf:/etc/mysql/conf.d/mysqld.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=root

  redis:
    image: redis:latest
    container_name: app-redis
    networks:
      - ondoor
    command: redis-server /usr/local/etc/redis/redis.conf --appendonly yes
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis/data:/data
    ports:
        - "6379:6379"
